In [2]:
import tensorflow as tf


# A Toy Example

In [ ]:
param = tf.Variable([1.0])
with tf.GradientTape() as tape:
    loss = (param - 3) ** 2
grad = tape.gradient(loss, param)
print("Gradient before step:", grad)
w  = tf.Variable([1.0, 2.0])
x  = tf.Variable([4.0, 6.0])
with tf.GradientTape() as tape:
  y = w * x
tape.gradient(y, w)



In [3]:


# Normally, the input sample has more than 1 example. Let's take `num_example=2`. 
num_example = 2
tf.random.set_seed(22)
W = tf.Variable(tf.random.normal((2, 10)))
X = tf.constant(tf.random.normal((10, num_example)))
print('W:', W.numpy())
print('X:', X.numpy())

 
with  tf.GradientTape() as tape:
    z = tf.matmul(W, X)
    print('z:', z.numpy())

dz_dW = tape.gradient(z, W)
dz_dW

# The gradients w.r.t `W` we got are summed from two examples. 
# For example, since the gradient w.r.t w1 or `W[0]` equals to x1 or `X[0]`, 
# here we got 0.2138209(= -0.12328745+0.33710834). 
# However, during the backward pass of neural network, 
# we average the gradients across training examples(considering the learning rate, it doesnot necessarily need to be averaged). 
# Some common misunderstanding may be found [here](https://datascience.stackexchange.com/questions/33489/why-averaging-the-gradient-works-in-gradient-descent).
# However, if the function output is a vector, it would compute the gradients of vector's sum. 
# Check [`jacobian`](https://www.tensorflow.org/api_docs/python/tf/GradientTape#jacobian) for computing autodiff for each element in the output vector.


W: [[-0.7258272   1.0123503  -0.7519852  -0.88858026 -2.0784743   0.13739629
   0.24744615 -0.42350662 -1.5114709  -0.39976093]
 [-0.6800961  -0.11622717 -0.24688219 -0.40650508  0.7409944   1.0018212
  -0.00657086 -1.2199409  -0.8227369  -2.096853  ]]
X: [[-0.12328736  0.33710814]
 [-0.15698127  0.51004434]
 [ 0.77993774 -0.12912273]
 [ 0.28278875  1.2848064 ]
 [-0.3107411   1.5029539 ]
 [-0.35227138 -0.80474746]
 [-0.30448258 -0.9182585 ]
 [-0.27900812  1.9815253 ]
 [-0.14969558  1.0174019 ]
 [-1.9002974  -0.3961953 ]]
z: [[ 0.7189936 -6.453113 ]
 [ 3.6615932 -2.8890827]]


<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.21382079,  0.35306305,  0.650815  ,  1.5675951 ,  1.1922128 ,
        -1.1570189 , -1.2227411 ,  1.7025172 ,  0.86770636, -2.2964926 ],
       [ 0.21382079,  0.35306305,  0.650815  ,  1.5675951 ,  1.1922128 ,
        -1.1570189 , -1.2227411 ,  1.7025172 ,  0.86770636, -2.2964926 ]],
      dtype=float32)>

In [14]:
import numpy as np
v = np.random.randn(25)
v = tf.Variable(v)
print(v)
with tf.GradientTape() as tape:
    out =  (v+1) ** 2
grad = tape.gradient(out, v)
print(grad)

<tf.Variable 'Variable:0' shape=(25,) dtype=float64, numpy=
array([-0.3473799 ,  0.49434512,  0.77298346,  1.08673934,  0.69588929,
        0.68267483,  0.29298751, -0.61848185,  0.01832627,  0.06835366,
        0.62955296, -0.39228602,  0.45002156,  0.23983424, -0.99758659,
       -0.21402083, -0.18942877,  1.3108772 , -2.02840606, -0.10437081,
       -1.2195235 ,  0.24866279,  1.31752354,  0.217997  ,  0.83953719])>
tf.Tensor(
[ 1.3052402   2.98869023  3.54596692  4.17347868  3.39177859  3.36534966
  2.58597501  0.7630363   2.03665253  2.13670732  3.25910592  1.21542797
  2.90004312  2.47966848  0.00482683  1.57195835  1.62114246  4.6217544
 -2.05681213  1.79125839 -0.439047    2.49732557  4.63504709  2.43599401
  3.67907437], shape=(25,), dtype=float64)
