In [1]:
import numpy as np

## Vector and Matrix in Python

In [7]:
# define a vector with length 4
v = np.array([1, 2, 3, 4])
print(v)

# define a two-dimensional matrix
m = np.array([[1, 2], 
              [3, 4]])
print(m.shape)
# v.dot()


[1 2 3 4]
(2, 2)


What is "dimension" of the matrix `m`?

In [8]:
# the term "dimension" has a specific meaning that is distinct from how it's used to describe the shape of arrays in programming. 
# Note that the dimension of a vector space (or simply a space) refers to the number of vectors in a basis for the space.
# print('v shape', v.shape)
# 3blue1brown
print('m shape', m.shape)

m shape (2, 2)


Transpose $x^T$

In [9]:
# x.T
print('m:', m)
print('m.T', m.transpose())
print('m.T shape', m.T.shape)
# in numpy, a vector equals to the transpose of the vector


m: [[1 2]
 [3 4]]
m.T [[1 3]
 [2 4]]
m.T shape (2, 2)


Multipication (Dot Product) of Vector

In [10]:
x1 = np.array([1, 2,])
x2 = np.array([1, 2])
x1.dot(x2)

5

Matrices can be multiplied together in two ways.


In [11]:
# dot product of two matrices
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])

print(A.dot(B))


[[19 22]
 [43 50]]


Element wise: when two matrices have the same dimensions, matrix elements in the same position in each matrix are multiplied together
In python this uses the '$*$' operator.
```python
A = B * C
```


In [12]:
A * B

array([[ 5, 12],
       [21, 32]])

Matrix multiplication (Dot Product): when the number of columns in the first matrix is the same as the number of rows in the second.
In python this uses the '$@$' operator

In [ ]:
# matrix multiplication (dot product)

# define two matrices
A = np.random.randn(4,3)
print(np.shape(A))
print(A)
# print(A.dot(A)) # Error

C = np.random.randn(3,2)
# print(np.dot(A,C))
# print(A @ C)
print(A.dot(C))
print(A.dot(C).shape)

## Vector-Matrix Multiplication (Linear Transformation of Data)
See [this AWESOME video](https://www.youtube.com/watch?v=kYB8IZa5AuE)

<img src="pics/transformed_data_point.png" width=450>

In [13]:
# Define the vector v
v = np.array([1, 0])

# Define the rotation matrix A for a 90-degree rotation counterclockwise
A = np.array([[0, -1], 
              [1,  0]])

# v @ A -> [0, -1]

# Perform the matrix-vector multiplication (linear transformation)
v_transformed = np.dot(v, A)

# Print the original and transformed vectors
print("Original vector:", v)
print("Transformed vector:", v_transformed)


Original vector: [1 0]
Transformed vector: [ 0 -1]


Another Real Example: Language Transformed by a Matrix in Large Language Models (See [this paper](https://aclanthology.org/P19-1356.pdf) for details)

<img src="pics/language-transform1.png" width=350>
<img src="pics/language-transform.png" width=70>

<!-- PP: In "She sat on the chair," "on the chair" is a prepositional phrase that tells where she sat.
ADJP: in "The man with the blue hat is tall," "with the blue hat" functions as an adjective phrase modifying "man."
VP: In the sentence "The cat is sleeping on the mat," "is sleeping on the mat" is the VP.
NP: in "The quick brown fox jumps over the lazy dog," "the quick brown fox" and "the lazy dog" are both NPs. -->